import Navbar from "@/components/Navbar/Navbar";
import AuthContextProvider from "@/context/authContext";
import { GlobalStyle } from "@/styles/globalStyles";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Demo app primer nivel</title>
      </head>
      <body>
        {/* <Navbar></Navbar> */}
        <AuthContextProvider>
          <GlobalStyle />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
