import NavbarDashboard from "@/components/NavBarDashboard/NavBarDashboard"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <head>
          <title>Demo app about</title>
        </head>
        <body>
            {/* <NavbarDashboard></NavbarDashboard> */}
          {/* <h1>Layout!</h1> */}
          {children}
          </body>
      </html>
    )
  }
  